### ISSUE TITLE
Game unwinnable without taking chances

### ISSUE THREAD

**Issue by tilkinsc** [rdlf0/minesweeper#51]
**Describe the bug**
Stalemate games arent resolvable,

**To Reproduce**
1. isolate a board down to an 'either or' mine
2. place flag to determine which is which
3. dont win
4. take a 50/50 chance to win

**Expected behavior**
Flagging all mines should win the game

**Screenshots**
![image](https://user-images.githubusercontent.com/7494772/152656517-f7f43ec6-92f6-467b-8edf-1f11a11fa35d.png)

**URL Hash**
[Please add the URL hash (or the whole URL)](https://theminesweeper.com/#Cy5SHUCYIEFiQACgIgEACACYIAAKAIQAQQoJDTAAEBkokJEAQzAAAWAAqABoiEMBAZAEBowLIAB4CgoAgQZM)

**Desktop (please complete the following information):**
Windows Firefox

**Comment by rdlf0** [comment]
Hi @tilkinsc! Thank you for submitting your feedback! Unfortunately, situations where the final outcome depends on chance can't be avoided, as these are randomly generated mines. In the original minesweeper, the game can be won only by revealing all non-mines. Flagging a cell doesn't definitely mean that it is a mine and can't be considered enough of a condition for winning the game.

**Comment by tilkinsc** [comment]
Perhaps this is a good suggestion for another 'mode'

**Comment by rdlf0** [comment]
Thank you for the suggestion @tilkinsc! It will be considered in the next releases of the game.
